<?xml version="1.0" encoding="UTF-8"?>
<SCL xmlns="http://www.iec.ch/61850/2003/SCL" version="2007" revision="B" release="4">
	<Header id="project"/>
	<Substation name="LMV" desc="110kV LEGO Substation">
		<VoltageLevel name="C42" desc="" nomFreq="50" numPhases="3">
			<Voltage unit="V" multiplier="k">22</Voltage>
			<Bay name="480" desc="J2.10">
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="478" desc="J2.9">
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="476" desc="J2.8">
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="474" desc="J2.7">
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="472" desc="J2.6">
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="442" desc="J2.5">
				<ConductingEquipment name="TD42" type="CAB" desc="180kVA"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="T402" desc="J2.4">
				<ConductingEquipment name="TBN" type="CAP" desc="3.6 MVAr"/>
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES06" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="TUC42" desc="J2.3">
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="ES14" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
			</Bay>
			<Bay name="432" desc="J2.2">
				<ConductingEquipment name="VT" type="VTR" desc=""/>
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
		</VoltageLevel>
		<VoltageLevel name="C41" desc="" nomFreq="50" numPhases="3">
			<Voltage unit="V" multiplier="k">22</Voltage>
			<Bay name="479" desc="J1.9">
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="477" desc="J1.8">
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="475" desc="J1.7">
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="473" desc="J1.6">
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="471" desc="J1.5">
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="T401" desc="J1.4">
				<ConductingEquipment name="TBN" type="CAP" desc="3.6 MVAr"/>
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES06" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="TUC41" desc="J1.3">
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="ES14" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
			</Bay>
			<Bay name="431" desc="J1.2">
				<ConductingEquipment name="VT" type="VTR" desc=""/>
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="412" desc="J1.1">
				<ConductingEquipment name="DS2" type="DIS" desc=""/>
				<ConductingEquipment name="SPARE" type="CAB" desc="70m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
		</VoltageLevel>
	</Substation>
	<Substation name="BESSVSIP" desc="">
		<VoltageLevel name="RMU" desc="" nomFreq="50" numPhases="3">
			<Voltage unit="V" multiplier="k">22</Voltage>
			<Bay name="BESS4" desc="C434">
				<ConductingEquipment name="BT04" type="CAB" desc=""/>
				<ConductingEquipment name="485" type="CAB" desc="470m"/>
				<ConductingEquipment name="4343-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4342-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4341-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4343-7" type="DIS" desc=""/>
				<ConductingEquipment name="4342-3" type="DIS" desc=""/>
				<ConductingEquipment name="4341-7" type="DIS" desc=""/>
				<ConductingEquipment name="4342" type="CBR" desc=""/>
			</Bay>
			<Bay name="BESS3" desc="C433">
				<ConductingEquipment name="BT03" type="CAB" desc=""/>
				<ConductingEquipment name="483" type="CAB" desc="470m"/>
				<ConductingEquipment name="4333-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4332-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4331-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4333-7" type="DIS" desc=""/>
				<ConductingEquipment name="4332-3" type="DIS" desc=""/>
				<ConductingEquipment name="4331-7" type="DIS" desc=""/>
				<ConductingEquipment name="4332" type="CBR" desc=""/>
			</Bay>
			<Bay name="BESS2" desc="C432">
				<ConductingEquipment name="BT02" type="CAB" desc=""/>
				<ConductingEquipment name="481" type="CAB" desc="470m"/>
				<ConductingEquipment name="4323-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4322-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4321-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4323-7" type="DIS" desc=""/>
				<ConductingEquipment name="4322-3" type="DIS" desc=""/>
				<ConductingEquipment name="4321-7" type="DIS" desc=""/>
				<ConductingEquipment name="4322" type="CBR" desc=""/>
			</Bay>
			<Bay name="BESS1" desc="C431">
				<ConductingEquipment name="BT01" type="CAB" desc=""/>
				<ConductingEquipment name="479" type="CAB" desc="470m"/>
				<ConductingEquipment name="4313-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4312-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4311-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4313-7" type="DIS" desc=""/>
				<ConductingEquipment name="4312-3" type="DIS" desc=""/>
				<ConductingEquipment name="4311-7" type="DIS" desc=""/>
				<ConductingEquipment name="4312" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU13" desc="C413">
				<ConductingEquipment name="RMU2" type="CAB" desc=""/>
				<ConductingEquipment name="TD41" type="CAB" desc=""/>
				<ConductingEquipment name="471" type="CAB" desc="470m"/>
				<ConductingEquipment name="4133-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4132-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4131-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4133-7" type="DIS" desc=""/>
				<ConductingEquipment name="4132-3" type="DIS" desc=""/>
				<ConductingEquipment name="4131-7" type="DIS" desc=""/>
				<ConductingEquipment name="4133" type="CBR" desc=""/>
				<ConductingEquipment name="4132" type="CBR" desc=""/>
				<ConductingEquipment name="4131" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU12" desc="C412">
				<ConductingEquipment name="RMU2" type="CAB" desc=""/>
				<ConductingEquipment name="T12" type="CAB" desc=""/>
				<ConductingEquipment name="471" type="CAB" desc="470m"/>
				<ConductingEquipment name="4123-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4122-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4121-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4123-7" type="DIS" desc=""/>
				<ConductingEquipment name="4122-3" type="DIS" desc=""/>
				<ConductingEquipment name="4121-7" type="DIS" desc=""/>
				<ConductingEquipment name="4123" type="CBR" desc=""/>
				<ConductingEquipment name="4122" type="CBR" desc=""/>
				<ConductingEquipment name="4121" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU11" desc="C411">
				<ConductingEquipment name="RMU2" type="CAB" desc=""/>
				<ConductingEquipment name="T11" type="CAB" desc=""/>
				<ConductingEquipment name="471" type="CAB" desc="470m"/>
				<ConductingEquipment name="4113-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4112-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4111-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4113-7" type="DIS" desc=""/>
				<ConductingEquipment name="4112-3" type="DIS" desc=""/>
				<ConductingEquipment name="4111-7" type="DIS" desc=""/>
				<ConductingEquipment name="4113" type="CBR" desc=""/>
				<ConductingEquipment name="4112" type="CBR" desc=""/>
				<ConductingEquipment name="4111" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU10" desc="C410">
				<ConductingEquipment name="RMU2" type="CAB" desc=""/>
				<ConductingEquipment name="T10" type="CAB" desc=""/>
				<ConductingEquipment name="471" type="CAB" desc="470m"/>
				<ConductingEquipment name="4103-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4102-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4101-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4103-7" type="DIS" desc=""/>
				<ConductingEquipment name="4102-3" type="DIS" desc=""/>
				<ConductingEquipment name="4101-7" type="DIS" desc=""/>
				<ConductingEquipment name="4103" type="CBR" desc=""/>
				<ConductingEquipment name="4102" type="CBR" desc=""/>
				<ConductingEquipment name="4101" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU9" desc="C409">
				<ConductingEquipment name="RMU2" type="CAB" desc=""/>
				<ConductingEquipment name="T09" type="CAB" desc=""/>
				<ConductingEquipment name="471" type="CAB" desc="470m"/>
				<ConductingEquipment name="4093-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4092-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4091-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4093-7" type="DIS" desc=""/>
				<ConductingEquipment name="4092-3" type="DIS" desc=""/>
				<ConductingEquipment name="4091-7" type="DIS" desc=""/>
				<ConductingEquipment name="4093" type="CBR" desc=""/>
				<ConductingEquipment name="4092" type="CBR" desc=""/>
				<ConductingEquipment name="4091" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU8" desc="C408">
				<ConductingEquipment name="RMU2" type="CAB" desc=""/>
				<ConductingEquipment name="T08" type="CAB" desc=""/>
				<ConductingEquipment name="471" type="CAB" desc="470m"/>
				<ConductingEquipment name="4083-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4082-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4081-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4083-7" type="DIS" desc=""/>
				<ConductingEquipment name="4082-3" type="DIS" desc=""/>
				<ConductingEquipment name="4081-7" type="DIS" desc=""/>
				<ConductingEquipment name="4083" type="CBR" desc=""/>
				<ConductingEquipment name="4082" type="CBR" desc=""/>
				<ConductingEquipment name="4081" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU7" desc="C407">
				<ConductingEquipment name="RMU2" type="CAB" desc=""/>
				<ConductingEquipment name="T07" type="CAB" desc=""/>
				<ConductingEquipment name="471" type="CAB" desc="470m"/>
				<ConductingEquipment name="4073-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4072-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4071-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4073-7" type="DIS" desc=""/>
				<ConductingEquipment name="4072-3" type="DIS" desc=""/>
				<ConductingEquipment name="4071-7" type="DIS" desc=""/>
				<ConductingEquipment name="4073" type="CBR" desc=""/>
				<ConductingEquipment name="4072" type="CBR" desc=""/>
				<ConductingEquipment name="4071" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU6" desc="C406">
				<ConductingEquipment name="RMU2" type="CAB" desc=""/>
				<ConductingEquipment name="T06" type="CAB" desc=""/>
				<ConductingEquipment name="471" type="CAB" desc="470m"/>
				<ConductingEquipment name="4063-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4062-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4061-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4063-7" type="DIS" desc=""/>
				<ConductingEquipment name="4062-3" type="DIS" desc=""/>
				<ConductingEquipment name="4061-7" type="DIS" desc=""/>
				<ConductingEquipment name="4063" type="CBR" desc=""/>
				<ConductingEquipment name="4062" type="CBR" desc=""/>
				<ConductingEquipment name="4061" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU5" desc="C405">
				<ConductingEquipment name="RMU6" type="CAB" desc=""/>
				<ConductingEquipment name="T05" type="CAB" desc=""/>
				<ConductingEquipment name="RMU5" type="CAB" desc="470m"/>
				<ConductingEquipment name="4053-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4052-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4051-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4053-7" type="DIS" desc=""/>
				<ConductingEquipment name="4052-3" type="DIS" desc=""/>
				<ConductingEquipment name="4051-7" type="DIS" desc=""/>
				<ConductingEquipment name="4053" type="CBR" desc=""/>
				<ConductingEquipment name="4052" type="CBR" desc=""/>
				<ConductingEquipment name="4051" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU4" desc="C404">
				<ConductingEquipment name="RMU5" type="CAB" desc=""/>
				<ConductingEquipment name="T04" type="CAB" desc=""/>
				<ConductingEquipment name="RMU4" type="CAB" desc="470m"/>
				<ConductingEquipment name="4043-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4042-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4041-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4043-7" type="DIS" desc=""/>
				<ConductingEquipment name="4042-3" type="DIS" desc=""/>
				<ConductingEquipment name="4041-7" type="DIS" desc=""/>
				<ConductingEquipment name="4043" type="CBR" desc=""/>
				<ConductingEquipment name="4042" type="CBR" desc=""/>
				<ConductingEquipment name="4041" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU3" desc="C403">
				<ConductingEquipment name="RMU4" type="CAB" desc=""/>
				<ConductingEquipment name="T03" type="CAB" desc=""/>
				<ConductingEquipment name="RMU3" type="CAB" desc="470m"/>
				<ConductingEquipment name="4033-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4032-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4031-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4033-7" type="DIS" desc=""/>
				<ConductingEquipment name="4032-3" type="DIS" desc=""/>
				<ConductingEquipment name="4031-7" type="DIS" desc=""/>
				<ConductingEquipment name="4033" type="CBR" desc=""/>
				<ConductingEquipment name="4032" type="CBR" desc=""/>
				<ConductingEquipment name="4031" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU2" desc="C402">
				<ConductingEquipment name="RMU3" type="CAB" desc=""/>
				<ConductingEquipment name="T02" type="CAB" desc=""/>
				<ConductingEquipment name="RMU2" type="CAB" desc="470m"/>
				<ConductingEquipment name="4023-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4022-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4021-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4023-7" type="DIS" desc=""/>
				<ConductingEquipment name="4022-3" type="DIS" desc=""/>
				<ConductingEquipment name="4021-7" type="DIS" desc=""/>
				<ConductingEquipment name="4023" type="CBR" desc=""/>
				<ConductingEquipment name="4022" type="CBR" desc=""/>
				<ConductingEquipment name="4021" type="CBR" desc=""/>
			</Bay>
			<Bay name="RMU1" desc="C401">
				<ConductingEquipment name="RMU2" type="CAB" desc=""/>
				<ConductingEquipment name="T01" type="CAB" desc=""/>
				<ConductingEquipment name="471" type="CAB" desc="470m"/>
				<ConductingEquipment name="4013-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4012-38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4011-76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="RMU" bayName="RMU1" connectivityNode="BESSVSIP/RMU/RMU1/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="4013-7" type="DIS" desc=""/>
				<ConductingEquipment name="4012-3" type="DIS" desc=""/>
				<ConductingEquipment name="4011-7" type="DIS" desc=""/>
				<ConductingEquipment name="4013" type="CBR" desc=""/>
				<ConductingEquipment name="4012" type="CBR" desc=""/>
				<ConductingEquipment name="4011" type="CBR" desc=""/>
				<ConnectivityNode name="grounded" pathName="BESSVSIP/RMU/RMU1/grounded"/>
			</Bay>
		</VoltageLevel>
		<VoltageLevel name="C42" desc="22kV" nomFreq="50" numPhases="3">
			<Voltage unit="V" multiplier="k">22</Voltage>
			<Bay name="472" desc="J2.2">
				<ConductingEquipment name="RMU7" type="CAB" desc="1035m"/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="474" desc="J2.3">
				<ConductingEquipment name="SPARE" type="CAB" desc=""/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="476" desc="J2.4">
				<ConductingEquipment name="RMU8" type="CAB" desc="250m"/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="478" desc="J2.5">
				<ConductingEquipment name="LMV_480" type="CAB" desc="1575m"/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="480" desc="J2.6">
				<ConductingEquipment name="SPARE" type="CAB" desc=""/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="TUC42" desc="J2.7">
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="ES24" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
			</Bay>
			<Bay name="482" desc="J2.8">
				<ConductingEquipment name="SPARE" type="CAB" desc=""/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
		</VoltageLevel>
		<VoltageLevel name="C41" desc="22kV" nomFreq="50" numPhases="3">
			<Voltage unit="V" multiplier="k">22</Voltage>
			<Bay name="412" desc="J1.1">
				<ConductingEquipment name="Coupler cable" type="CAB" desc="12m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="DS2" type="DIS" desc=""/>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="471" desc="J1.2">
				<ConductingEquipment name="RMU1" type="CAB" desc="470m"/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
				<ConnectivityNode name="grounded" pathName="BESSVSIP/C41/471/grounded"/>
			</Bay>
			<Bay name="473" desc="J1.3">
				<ConductingEquipment name="SPARE" type="CAB" desc=""/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="475" desc="J1.4">
				<ConductingEquipment name="RMU12" type="CAB" desc="795m"/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="477" desc="J1.5">
				<ConductingEquipment name="LMV_479" type="CAB" desc="1450m"/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="TD41" desc="J1.6">
				<ConductingEquipment name="TD" type="AXN" desc="105m"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES38" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="479" desc="J1.7">
				<ConductingEquipment name="BESS1" type="CAB" desc="70m"/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="481" desc="J1.8">
				<ConductingEquipment name="BESS2" type="CAB" desc="75m"/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="483" desc="J1.9">
				<ConductingEquipment name="BESS3" type="CAB" desc="60m"/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="485" desc="J1.10">
				<ConductingEquipment name="BESS4" type="CAB" desc="70m"/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
			<Bay name="TUC41" desc="J1.11">
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="ES14" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
			</Bay>
			<Bay name="487" desc="J1.12">
				<ConductingEquipment name="SPARE" type="CAB" desc=""/>
				<ConductingEquipment name="VT" type="VTR" desc="22/0.11"/>
				<ConductingEquipment name="CT" type="CTR" desc="800/1"/>
				<ConductingEquipment name="ES76" type="DIS" desc="">
					<Terminal name="T1" cNodeName="grounded" substationName="BESSVSIP" voltageLevelName="C41" bayName="471" connectivityNode="BESSVSIP/C41/471/grounded"/>
				</ConductingEquipment>
				<ConductingEquipment name="CB" type="CBR" desc=""/>
			</Bay>
		</VoltageLevel>
	</Substation>
</SCL>